In [1]:
import pandas as pd
import numpy as np

data=pd.read_csv('task3_2021.training.csv')
data['target'].value_counts()

##Selecting variables##
target=data['target']
training=data.loc[:,data.columns!='target']
training.head()

In [4]:
##Read in Testing data##
data2=pd.read_csv('task3_2021.test.csv')
data2.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18
0,12.981599,14.926975,14.055879,12.940302,6.547128,3.765283,4.911310,12.816209,12.321573,17.026134,-4.435416,-3.338954,5.145203,0.790691,-2.833418,E,D,A,-3.198949
1,26.898603,8.866915,20.358121,6.067027,13.505201,1.742242,3.731071,14.026740,13.686651,17.920196,3.398008,-4.949895,2.115480,1.839801,2.199004,F,F,E,10.497858
2,20.817003,5.789936,20.937223,8.249511,13.569874,0.060766,5.505705,7.102595,12.735801,7.195690,10.580991,-5.864917,-2.386709,2.558099,5.790495,F,F,F,-11.909326
3,9.994456,12.242201,7.906568,10.475264,14.327991,0.856716,4.754537,26.673467,6.219800,21.140358,-11.304655,-8.923086,5.620824,1.436804,-6.877449,C,B,A,-0.256432
4,8.640119,11.944469,14.674074,13.246914,5.013325,2.332369,4.226819,6.004056,11.400005,6.236202,1.708020,12.079740,16.079740,1.037320,5.126897,A,C,D,12.142437

In [9]:
##Label Encoding##
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
training_lb=pd.DataFrame(training)
training_lb['f15']=lb.fit_transform(training_lb['f15'])
training_lb['f16']=lb.fit_transform(training_lb['f16'])
training_lb['f17']=lb.fit_transform(training_lb['f17'])
training_lb.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18
0,14.557571,11.846020,15.020207,2.623484,15.538517,2.341611,5.829028,7.586709,13.331953,8.304782,-8.980424,-1.978135,-9.056215,0.601958,-3.990212,5,5,0,-8.435632
1,17.031884,4.314536,19.694838,15.264186,7.054585,0.382333,4.650885,11.331481,12.492329,12.877221,-1.788222,-12.520625,1.183564,2.312428,-5.997316,5,0,5,13.314504
2,24.986272,6.139161,21.949963,5.590123,16.445212,2.213986,2.393948,16.885378,8.114116,20.133208,12.148553,-11.400213,15.273799,2.714855,6.574276,0,2,5,8.964849
3,7.584971,11.598161,9.793109,11.873020,6.645073,3.346882,4.445008,13.218360,8.495786,17.403693,-3.371434,-1.329931,4.307364,1.217894,-1.730330,3,3,1,13.563612
4,11.625079,12.517998,15.522108,18.269750,1.508771,3.078033,5.224333,18.335198,9.604704,19.732707,3.192207,2.195230,10.903963,2.317327,1.379398,1,2,1,-8.590211

In [10]:
##Label Encoding(test)##
lb=LabelEncoder()
test_lb=pd.DataFrame(data2)
test_lb['f15']=lb.fit_transform(test_lb['f15'])
test_lb['f16']=lb.fit_transform(test_lb['f16'])
test_lb['f17']=lb.fit_transform(test_lb['f17'])
test_lb.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18
0,12.981599,14.926975,14.055879,12.940302,6.547128,3.765283,4.911310,12.816209,12.321573,17.026134,-4.435416,-3.338954,5.145203,0.790691,-2.833418,4,3,0,-3.198949
1,26.898603,8.866915,20.358121,6.067027,13.505201,1.742242,3.731071,14.026740,13.686651,17.920196,3.398008,-4.949895,2.115480,1.839801,2.199004,5,5,4,10.497858
2,20.817003,5.789936,20.937223,8.249511,13.569874,0.060766,5.505705,7.102595,12.735801,7.195690,10.580991,-5.864917,-2.386709,2.558099,5.790495,5,5,5,-11.909326
3,9.994456,12.242201,7.906568,10.475264,14.327991,0.856716,4.754537,26.673467,6.219800,21.140358,-11.304655,-8.923086,5.620824,1.436804,-6.877449,2,1,0,-0.256432
4,8.640119,11.944469,14.674074,13.246914,5.013325,2.332369,4.226819,6.004056,11.400005,6.236202,1.708020,12.079740,16.079740,1.037320,5.126897,0,2,3,12.142437

In [11]:
nor = pd.concat([training_lb,test_lb])
from sklearn import preprocessing
test2 = nor.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(test2)
nor = pd.DataFrame(x_scaled)
nor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.329215,0.653793,0.563730,0.090143,0.807746,0.585368,0.971529,0.060935,0.777665,0.144040,0.423383,0.486251,0.275332,0.420316,0.348450,1.0,1.0,0.0,0.204050
1,0.424406,0.025965,0.855938,0.792450,0.336332,0.095489,0.775061,0.204979,0.707676,0.429841,0.518804,0.260084,0.476421,0.638770,0.287334,1.0,0.0,1.0,0.967090
2,0.730423,0.178067,0.996905,0.254967,0.858127,0.553458,0.398693,0.418613,0.342715,0.883379,0.703707,0.284120,0.753126,0.690166,0.670134,0.0,0.4,1.0,0.814495
3,0.060969,0.633131,0.236987,0.604040,0.313577,0.836717,0.740729,0.277559,0.374530,0.712770,0.497799,0.500157,0.537767,0.498981,0.417262,0.6,0.6,0.2,0.975829
4,0.216398,0.709809,0.595104,0.959437,0.028176,0.769496,0.870689,0.474381,0.466968,0.858345,0.584881,0.575783,0.667311,0.639395,0.511952,0.2,0.4,0.2,0.198627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,0.580787,0.027045,0.862440,0.246717,0.819581,0.191666,0.900701,0.613363,0.055177,0.891451,0.675194,0.455162,0.590375,0.662719,0.637414,0.2,0.2,1.0,0.574430
11996,0.039540,0.658594,0.184455,0.049928,0.899695,0.846978,0.336913,0.313908,0.496136,0.439431,0.240530,0.278598,0.465351,0.420488,0.391880,0.8,0.0,1.0,0.779248
11997,0.965270,0.457001,0.854306,0.087903,0.725440,0.247298,0.977218,0.194333,0.835256,0.611575,0.629968,0.394198,0.527319,0.619182,0.585515,0.6,0.6,1.0,0.612511
11998,0.092472,0.678180,0.085254,0.496937,0.669855,0.503558,0.774043,0.481719,0.026672,0.964464,0.460033,0.666418,0.648872,0.619409,0.493920,0.0,0.8,1.0,0.716952
11999,0.301770,0.505643,0.666023,0.778966,0.044356,0.821844,0.542827,0.459906,0.318190,0.959865,0.675507,0.451005,0.643747,0.613854,0.490157,0.4,0.0,0.6,0.826856

In [15]:
training_lb = nor.iloc[0:10000,:]
test_lb = nor.iloc[10000:,:]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
10000,0.268585,0.910622,0.503450,0.663337,0.308135,0.941330,0.818490,0.262090,0.693442,0.689170,0.483683,0.457058,0.554220,0.444421,0.383674,0.8,0.6,0.0,0.387764
10001,0.803993,0.405453,0.897400,0.281463,0.694764,0.435507,0.621672,0.308654,0.807233,0.745054,0.587611,0.422498,0.494722,0.578408,0.536909,1.0,1.0,0.8,0.868276
10002,0.570025,0.148955,0.933599,0.402720,0.698358,0.015087,0.917611,0.042313,0.727971,0.074716,0.682909,0.402869,0.406308,0.670145,0.646268,1.0,1.0,1.0,0.082186
10003,0.153665,0.686818,0.119061,0.526382,0.740483,0.214099,0.792346,0.795116,0.184808,0.946331,0.392547,0.337262,0.563561,0.526939,0.260535,0.4,0.2,0.0,0.490993
10004,0.101562,0.661999,0.542093,0.680372,0.222908,0.583057,0.704344,0.000057,0.616621,0.014743,0.565189,0.787835,0.768953,0.475919,0.626062,0.0,0.4,0.6,0.925971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,0.580787,0.027045,0.862440,0.246717,0.819581,0.191666,0.900701,0.613363,0.055177,0.891451,0.675194,0.455162,0.590375,0.662719,0.637414,0.2,0.2,1.0,0.574430
11996,0.039540,0.658594,0.184455,0.049928,0.899695,0.846978,0.336913,0.313908,0.496136,0.439431,0.240530,0.278598,0.465351,0.420488,0.391880,0.8,0.0,1.0,0.779248
11997,0.965270,0.457001,0.854306,0.087903,0.725440,0.247298,0.977218,0.194333,0.835256,0.611575,0.629968,0.394198,0.527319,0.619182,0.585515,0.6,0.6,1.0,0.612511
11998,0.092472,0.678180,0.085254,0.496937,0.669855,0.503558,0.774043,0.481719,0.026672,0.964464,0.460033,0.666418,0.648872,0.619409,0.493920,0.0,0.8,1.0,0.716952
11999,0.301770,0.505643,0.666023,0.778966,0.044356,0.821844,0.542827,0.459906,0.318190,0.959865,0.675507,0.451005,0.643747,0.613854,0.490157,0.4,0.0,0.6,0.826856

In [16]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
# load dataset

dataset = training_lb.values
#min_max_scaler = preprocessing.MinMaxScaler()
X = dataset[:,0:19].astype(float)
#X = dataset[:,0:11].astype(float)
Y = target.to_numpy()
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
dummy_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
def baseline_model():
    model = Sequential()
    model.add(Dense(175, input_dim=19, activation='relu'))
    model.add(Dense(175, activation='relu'))
    #model.add(Dense(115, activation='relu'))
    model.add(Dense(10, activation='softmax'))
	# Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [20]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=50, verbose=0)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

<ipython-input-20-a653d09169b7>:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  estimator = KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=50, verbose=0)

Baseline: 90.51% (1.10%)

In [22]:
estimator.fit(X, Y)
dic = {'Id': range(1,2001), 'Predicted': estimator.predict(test_lb)}
output = pd.DataFrame(dic)
output.to_csv("task3layer2epoch100.csv", index=False)